esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false

# Enable logging
logger:
  level: ${log_level}

web_server:
  port: 80
  log: false
  local: true
  version: 3

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption
  reboot_timeout: 0s

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:

captive_portal:

improv_serial:

button:
  - platform: restart
    id: restart_btn
    name: "Restart Controller"

time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/Zurich

sensor:
  - platform: uptime
    type: timestamp
    name: "Last Boot Time"
