substitutions:
  project_name: "Peterzhang.Doorman_PCB"
  project_version: "1.0"

packages:
  base: !include doorman-base.yaml
  interactive_setup: !include doorman-interactive-setup.yaml
  pattern_events: !include doorman-pattern-events.yaml
  ring_to_open: !include doorman-ring-to-open.yaml
  
tc_bus:
  rx_pin: 9
  tx_pin: 10

esphome:
  project:
    name: ${project_name}
    version: ${project_version}